### PR TITLE
Support for root user reset-password action

### PR DESCRIPTION
**Pull request by vipulsabhaya**
I've implemented 'reset-password' as an additional action on an instance.  We have stubbed out the user and database management portions of the Reddwarf API and return a 501 Not Implemented.

### CODE REVIEW

**Comment by hub-cap** [comment]
Lets hold off on merging this until we can get something in reddwarf lite. It doesnt make sense to merge this w/o the lite code as well.

**Comment by vipulsabhaya** [comment]
I can submit a pull request to reddwarf-lite with a patch.  Would you like to see it stubbed out and return Not Implemented?

**Comment by rnirmal** [comment]
Yeah that should probably be enough.

**Comment by ed-** [comment]
Nailed it.

If we merge this one before #24 I'll bridge the gap, I want dashed arguments.

**Comment by ed-** [comment]
@vipulsabhaya, we merged #24 first, so would you please revisit this PR to use the `self.id` and `CommandsBase._pretty_print`? It was a fairly drastic change, with the addition of CommandsBase and the way parameters are passed to the command handlers.

**Comment by ed-** [comment]
+1

**Comment by jcru** [comment]
+1

**Pull request merged**
