### PR TITLE
Changing Reddwarf client to use its own request function.

### PR DESCRIPTION
**Pull request by TimSimpsonR**
- Nova client changed in a way that broke our client, so copying the code from there is necessary.
- Adding InstanceStatus class with the status strings.

### CODE REVIEW

**Comment by rnirmal** [comment]
hmm we might want to push back or find out why that change happened in nova-client...btw +1 on this.

**Comment by cp16net** [comment]
I agree with @rnirmal we need to find out why they thought that was a good idea. 
+1 :godmode:

**Comment by TimSimpsonR** [comment]
Quick note: I changed this a bit after I realized my fix broke the Exception types inherited from the Nova client. The tests run clean green in fake mode now.

@cp16net  and @rnirmal Their change makes sense, they wanted to be sure codes from 400 up which were not explicitly handled by a custom exception type (such as 422, in their case) would get some kind of default exception. Maybe we could see about merging our UnprocessableEntity exception into the Nova client code base.

**Comment by ed-** [comment]
Yes. Yes, do this.
+1

**Pull request merged**
