### PR TITLE
Added a "pretty_print" option which makes captured output look even better.

### PR DESCRIPTION
**Pull request by TimSimpsonR**
- Shows a possibly usable curl statement which includes the request body.
- Also prints the request and response body as well formated, easy to read JSON.
- Specify RDC_PP while running tests to see the http communication in this format in any logged test failures.

### CODE REVIEW

**Comment by TimSimpsonR** [comment]
This is something I added locally during a really frustrating debug session with some RDL feature. I was about to rebase it out of existence and thought I'd submit it here.  I like that I can easily copy and paste the curl statement (without manually mucking with adding the body) and also refer to the request body.

This is what a failed test looks like if you specify RDC_PP=True:

<pre><code>
======================================================================
FAIL: test_create (tests.api.instances.CreateInstance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/hgfs/Ridley/reddwarf_lite-integration/tests/integration/tests/api/instances.py", line 297, in test_create
    fail("FAIL!")
AssertionError: FAIL!
-------------------- >> begin captured logging 
reddwarfclient.client: DEBUG: REQUEST:
reddwarfclient.client: DEBUG: curl -i http://localhost:8779/v1.0/6e45a760df154dbab4fb041e65a30d9c/instances -X POST -H "X-Auth-Project-Id: reddwarf" -H "User-Agent: python-reddwarfclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: f8c105a28c4e494487d5828f233a771f" -d '{"instance": {"volume": null, "users": [{"password": "litepass", "name": "lite", "databases": [{"name": "firstdb"}]}], "flavorRef": "https://localhost:8779/v1.0/6e45a760df154dbab4fb041e65a30d9c/flavors/7", "name": "TEST_2012-07-10 09:02:26.720840", "databases": [{"collate": "latin2_general_ci", "name": "firstdb", "character_set": "latin2"}, {"name": "db2"}]}}'
reddwarfclient.client: DEBUG: BODY: {
    "instance": {
        "databases": [
            {
                "character_set": "latin2", 
                "collate": "latin2_general_ci", 
                "name": "firstdb"
            }, 
            {
                "name": "db2"
            }
        ], 
        "flavorRef": "https://localhost:8779/v1.0/6e45a760df154dbab4fb041e65a30d9c/flavors/7", 
        "name": "TEST_2012-07-10 09:02:26.720840", 
        "users": [
            {
                "databases": [
                    {
                        "name": "firstdb"
                    }
                ], 
                "name": "lite", 
                "password": "litepass"
            }
        ], 
        "volume": null
    }
}

reddwarfclient.client: DEBUG: RESPONSE HEADERS: {'date': 'Tue, 10 Jul 2012 16:02:26 GMT', 'status': '200', 'content-length': '663', 'content-type': 'application/json'}
reddwarfclient.client: DEBUG: RESPONSE BODY   : {
    "instance": {
        "created": "2012-07-10T16:02:26", 
        "flavor": {
            "id": "7", 
            "links": [
                {
                    "href": "https://localhost:8779/v1.0/6e45a760df154dbab4fb041e65a30d9c/flavors/7", 
                    "rel": "self"
                }, 
                {
                    "href": "https://localhost:8779/flavors/7", 
                    "rel": "bookmark"
                }
            ]
        }, 
        "id": "0c200579-cda7-4aa6-914c-1dcb04beaf93", 
        "links": [
            {
                "href": "https://localhost:8779/v1.0/6e45a760df154dbab4fb041e65a30d9c/instances/0c200579-cda7-4aa6-914c-1dcb04beaf93", 
                "rel": "self"
            }, 
            {
                "href": "https://localhost:8779/instances/0c200579-cda7-4aa6-914c-1dcb04beaf93", 
                "rel": "bookmark"
            }
        ], 
        "name": "TEST_2012-07-10 09:02:26.720840", 
        "status": "BUILD", 
        "updated": "2012-07-10T16:02:26", 
        "volume": {
            "size": null
        }
    }
}
---------------------  end captured logging << ---------------------

</code></pre>

**Comment by cp16net** [comment]
This is really cool i could see that making the log files VERY LONG so i might suggest not turning this feature on in CI.

**Comment by cp16net** [comment]
+1

**Comment by ed-** [comment]
+1

**Comment by jcru** [comment]
+1

**Comment by imsplitbit** [comment]
+1

**Comment by pdmars** [comment]
+1

**Comment by rnirmal** [comment]
+1

**Pull request merged**
